Gestionale_Pizzeria/Controllers/OrdiniController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gestionale_Pizzeria.Models;

namespace Gestionale_Pizzeria.Controllers
{
    public class OrdiniController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Ordini
        public ActionResult Index()
        {
            var ordini = db.Ordini.Include(o => o.DettagliOrdine).Include(o => o.Utenti);
            ViewBag.StatoPreparazione = "In Preparazione";
            return View(ordini.ToList());
        }

        // GET: Ordini/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordini ordini = db.Ordini.Find(id);
            if (ordini == null)
            {
                return HttpNotFound();
            }
            return View(ordini);
        }

        // GET: Ordini/Create
        public ActionResult Create()
        {
            //DettagliOrdine data = TempData["dettagliOrdine"] as DettagliOrdine;
            //TempData["quantitá"] = data.quantita;

            //ViewBag.IdOrdine = new SelectList(db.DettagliOrdine, "IdDettaglioOrdine", "nota");
            //ViewBag.IdOrdine = new SelectList(db.Utenti, "IdUtente", "Username");
            return View();
        }

        public ActionResult CreateNew()
        {
            //DettagliOrdine data = TempData["dettagliOrdine"] as DettagliOrdine;
            //TempData["quantitá"] = data.quantita;

            ViewBag.IdOrdine = new SelectList(db.DettagliOrdine, "IdDettaglioOrdine", "nota");
            ViewBag.IdOrdine = new SelectList(db.Utenti, "IdUtente", "Username");
            return View();
        }


        // POST: Ordini/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StatoOrdine")] Ordini ordini)
        {

            DettagliOrdine data = TempData["dettagliOrdine"] as DettagliOrdine;
            Utenti utente = TempData["Utente"] as Utenti;
            ordini.DataOrdine = DateTime.Now;
            ordini.StatoOrdine = "";
            ordini.Evaso = false;
            ordini.Importo = data.Prodotti.PrezzoVendita * data.quantita;
            ordini.Confermato = "Ordine confermato";
            ordini.IdUtente = utente.IdUtente;
      
            DettagliOrdine dettagli = new DettagliOrdine();
            //dettagli.IdOrdine = ;
            dettagli.nota = data.nota;
            dettagli.quantita = data.quantita;
            dettagli.Prodotti = data.Prodotti;
            dettagli.IdProdotto = data.Prodotti.IdProdotto;

            db.DettagliOrdine.Add(dettagli);
            db.SaveChanges(); 
            ordini.IdDettaglioOrdine = db.DettagliOrdine.Where(dOrder => dOrder.Ordini.DataOrdine.Equals(ordini.DataOrdine)).FirstOrDefault().IdDettaglioOrdine;
            db.Ordini.Add(ordini);            
            db.SaveChanges();
            return RedirectToAction("Index");
            

            //ViewBag.IdOrdine = new SelectList(db.DettagliOrdine, "IdDettaglioOrdine", "nota", ordini.IdOrdine);
            //ViewBag.IdOrdine = new SelectList(db.Utenti, "IdUtente", "Username", ordini.IdOrdine);
            //return View(ordini);
        }

        // GET: Ordini/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordini ordini = db.Ordini.Find(id);
            if (ordini == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdOrdine = new SelectList(db.DettagliOrdine, "IdDettaglioOrdine", "nota", ordini.IdOrdine);
            ViewBag.IdOrdine = new SelectList(db.Utenti, "IdUtente", "Username", ordini.IdOrdine);
            return View(ordini);
        }

        // POST: Ordini/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdOrdine,DataOrdine,Importo,StatoOrdine,Confermato,Evaso,IdDettaglioOrdine,IdUtente")] Ordini ordini)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ordini).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdOrdine = new SelectList(db.DettagliOrdine, "IdDettaglioOrdine", "nota", ordini.IdOrdine);
            ViewBag.IdOrdine = new SelectList(db.Utenti, "IdUtente", "Username", ordini.IdOrdine);
            return View(ordini);
        }

        // GET: Ordini/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordini ordini = db.Ordini.Find(id);
            if (ordini == null)
            {
                return HttpNotFound();
            }
            return View(ordini);
        }

        // POST: Ordini/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ordini ordini = db.Ordini.Find(id);
            db.Ordini.Remove(ordini);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestionale_Pizzeria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    <script src="https://kit.fontawesome.com/7b501ddc7c.js" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="header container-fluid d-flex justify-content-between align-items-center py-2 px-5">
        <div>
            <img src="~/Content/Logo/pizza-logo.jpg" class="logo-img" alt="Alternate Text" />
        </div>
        <div>
            <ul class="links-home d-flex gap-5">
                <li>@Html.ActionLink("Menu", "Index", "Home") <i class="fa-solid fa-house-user"></i></li>
                @if (!User.Identity.IsAuthenticated)
                {
                    <li class="btn btn-success text-white rounded btn-login">@Html.ActionLink("Login", "Signin", "Login") <i class="fa-solid fa-right-to-bracket"></i></li>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="btn btn-warning text-white rounded btn-login">@Html.ActionLink("Logout", "SignOut", "Login")</li>
                }
                <li>@Html.ActionLink("Register", "Signup", "Login") <i class="fa-solid fa-user-plus"></i></li>
            </ul>   
        </div>
        <div>
            @Html.ActionLink("Carrello", "Carrello", "Ordini") <i class="fa-solid fa-cart-shopping"></i>
        </div>      
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="container-fluid">
        <div class="footer">
            <footer class="d-flex flex-wrap justify-content-between align-items-center border-top p-4">
                <div class="col-md-4 d-flex align-items-center">
                    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                    </a>
                    <span class="mb-3 mb-md-0">© 2022 Company, Inc</span>
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3"><i class="fa-brands fa-linkedin"></i></li>
                    <li class="ms-3"><i class="fa-brands fa-instagram"></i></li>
                    <li class="ms-3"><i class="fa-brands fa-facebook"></i></li>
                </ul>
            </footer>
        </div>
    </div>
    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>