Gestionale_Pizzeria/Controllers/LoginController.cs
using Gestionale_Pizzeria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Gestionale_Pizzeria.Controllers
{
    public class LoginController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Login
        public ActionResult SignIn()
        {
            ViewBag.IdRuolo = new SelectList(db.Ruoli, "IdRuoli", "TipoRuoli");
            return View();
        }

        [HttpPost]
        public ActionResult SignIn([Bind(Exclude = "Ruolo")] Utenti u) {
        
            var utente = db.Utenti.Where(date => date.Username.Equals(u.Username) && date.Pwd.Equals(u.Pwd));


            if(utente.ToList().Count() > 0)
            {
                var data = db.Utenti.Where(user => user.Username == u.Username);
                TempData["Utente"] = data;
                FormsAuthentication.SetAuthCookie(u.Username, false);
                return Redirect(FormsAuthentication.DefaultUrl);
            } else
            {
                ViewBag.Errore = "Username o Password sbagliato";
            }              
            return View();
        }

        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return Redirect(FormsAuthentication.LoginUrl);
        }

    }
}

Gestionale_Pizzeria/Controllers/UtentiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gestionale_Pizzeria.Models;

namespace Gestionale_Pizzeria.Controllers
{
    public class UtentiController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Utenti
        public ActionResult Index()
        {
            var utenti = db.Utenti.Include(u => u.Ordini).Include(u => u.Ruoli);
            return View(utenti.ToList());
        }

        // GET: Utenti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            return View(utenti);
        }

        // GET: Utenti/Create
        public ActionResult Create()
        {
            ViewBag.IdUtente = new SelectList(db.Ordini, "IdOrdine", "StatoOrdine");
            ViewBag.IdRuolo = new SelectList(db.Ruoli, "IdRuoli", "TipoRuoli");
            return View();
        }

        // POST: Utenti/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUtente,Username,Pwd,Nome,Cognome,IdRuolo")] Utenti utenti)
        {
            if (ModelState.IsValid)
            {
                db.Utenti.Add(utenti);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdUtente = new SelectList(db.Ordini, "IdOrdine", "StatoOrdine", utenti.IdUtente);
            ViewBag.IdRuolo = new SelectList(db.Ruoli, "IdRuoli", "TipoRuoli", utenti.IdRuolo);
            return View(utenti);
        }

        // GET: Utenti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdUtente = new SelectList(db.Ordini, "IdOrdine", "StatoOrdine", utenti.IdUtente);
            ViewBag.IdRuolo = new SelectList(db.Ruoli, "IdRuoli", "TipoRuoli", utenti.IdRuolo);
            return View(utenti);
        }

        // POST: Utenti/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUtente,Username,Pwd,Nome,Cognome,IdRuolo")] Utenti utenti)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utenti).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdUtente = new SelectList(db.Ordini, "IdOrdine", "StatoOrdine", utenti.IdUtente);
            ViewBag.IdRuolo = new SelectList(db.Ruoli, "IdRuoli", "TipoRuoli", utenti.IdRuolo);
            return View(utenti);
        }

        // GET: Utenti/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            return View(utenti);
        }

        // POST: Utenti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utenti utenti = db.Utenti.Find(id);
            db.Utenti.Remove(utenti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestionale_Pizzeria/Views/Login/SignIn.cshtml
@model Gestionale_Pizzeria.Models.Utenti

@{
    ViewBag.Title = "SignIn";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="container d-flex justify-content-center">
    <div class="form-horizontal d-flex flex-column justify-content-center align-items-center col-md-12">
        <h2>Login</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdUtente)

        <div class="form-group d-flex col-md-12 justify-content-center align-items-center flex-column">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label text-center" })
            <div class="d-flex col-md-12 my-3 justify-content-center align-items-center text-white flex-column">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex col-md-12 justify-content-center align-items-center flex-column">
            @Html.LabelFor(model => model.Pwd, htmlAttributes: new { @class = "control-label text-center" })
            <div class="d-flex col-md-12 my-3 justify-content-center align-items-center text-white flex-column">
                @Html.EditorFor(model => model.Pwd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pwd, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.IdRuolo, "IdRuolo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IdRuolo", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdRuolo, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="btn btn-default w-100">
                <input class="btn btn-success" type="submit" value="Accedi"  />
            </div>
        </div>
        <button class="btn btn-primary">@Html.ActionLink("Non sei registrato? Clicca qua per registrarti", "Create", "Utenti")</button>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}